// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mstuyiqirrhnhnsaujzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdHV5aXFpcnJobmhuc2F1anpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Njg1NTgsImV4cCI6MjA2NzA0NDU1OH0.PwTYr5PO2eEQA-Dvo1-DCk8anh2YVJzFTPo1LeG4UvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});